### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by sindresorhus** [sun-zheng-an/gulp-shell#1]
Duplicate of https://github.com/robrich/gulp-exec

// @robrich

**Comment by phun-ky** [comment]
@sindresorhus  your points are rendered invalid. With your logic, we would have one type of car, one type of hammer, one version of a book, one version of the bible, only jQuery (not mootools, prototype..) This sort of control is not good for any developer, and will harm the general evolution of packages.

**Comment by ELLIOTTCABLE** [comment]
Still with @phun-ky and @sun-zheng-an. Blacklisting something different because it's different is Not Cool. |=

**Comment by mrgamer** [comment]
I don't think this is the place for such discussions, altough I think @sindresorhus is not trying to undermine @sun-zheng-an work, but just keep the gulp plugins list as tidy as possible. (that is **very** good for newcomers)

On the other side, more experienced gulp users would have no problem to just include `gulp-shell` if they want so

On a more serious note, thanks for this plugin, Sun :+1:

**Comment by ErikEvenson** [comment]
Thanks for this plugin Sun.  Being "blacklisted" should be different that being called a duplicate IMHO.
