### ISSUE TITLE
Only 16 files piped via src?

### ISSUE THREAD

**Issue by micros123** [sun-zheng-an/gulp-shell#15]
Great tool, however, it seems that when using wildcards in my gulp.src, only the first 16 files are being passed on to the shell. Any reason for this, and any way to override it?

**Comment by redben** [comment]
Apparently it is a bug in venyl-fs 0.3.1
https://github.com/gulpjs/gulp/issues/552

**Comment by gama410** [comment]
Just to make it clear because I personnaly didn't understand the reason behind the results being capped at 16 : the stream has to be consumed otherwise it will stop itself (thanks to @contra https://github.com/gulpjs/gulp/issues/716)
