### ISSUE TITLE
additional option to redirect console output to a file

### ISSUE THREAD

**Issue by seanpkps** [sun-zheng-an/gulp-shell#30]
If I run a command that writes to the console (stdout & stderr) I can suppress the output using _options.quiet: true_.

That's OK because I don't want to fill up my screen with this info, but if there's a problem, I want to be able to view that info to troubleshoot.

How about a new option: **redirect**
It would take a filename (relative to `process.cwd()`) and send the results of that output to it.

It looked like this could be done in the command and using a template, e.g.:
```
shell.task('npm install > <%= logfile %> 2>&1', {
	cwd: workspace_loc,
	templateData: {
		logfile: process.cwd() + path.sep + 'npm-install.log'
		}
	});
```

But that's a lot uglier, less readable, and makes a lot more boilerplate than:
```
shell.task('npm install', {cwd: workspace_loc, redirect: process.cwd() + path.sep + 'npm-install.log'});
```

Indeed, with a bit further testing, it seems like the redirect causes the task to indicate it's completed as soon as it starts writing to the file rather than once it actually completes, so it isn't really a solution.

**Comment by priestj** [comment]
Great idea I could really use this, especially for when you have a number of shell calls running at the same time, trying to debug can be a nightmare.

**Comment by seanpkps** [comment]
I forgot that I opened this issue ... @priestj - I made a package for this use case:
https://github.com/PointSource/gulp-command-task

I'm sure the interface is a bit crufty, but it does work.

**Comment by sun-zheng-an** [comment]
Sorry for replying so late.
I prefer to use the native way of redirection (with `>`) rather than add a new option.
