### ISSUE TITLE
The error handling will remove the color

### ISSUE THREAD

**Issue by hbrls** [sun-zheng-an/gulp-shell#38]
~~The Mocha's error logging is colorful. But the error handling will only print the text.~~

~~I did not notice this days before. I'm not sure now if I should use the native `npm run` instead of gulp.~~

**Comment by hbrls** [comment]
Sorry, it's the Mocha.

[It will disable color output if it sees that the thing it is outputting to is not a terminal.](http://stackoverflow.com/a/9137636/707580)

It seems that `exec` is not a terminal. Maybe you can mention that in the doc.

**Comment by Zolmeister** [comment]
for those using `gulp-mocha` ->  `mocha({useColors: true})`
