### ISSUE TITLE
Error was not caught when using `|` to pipe

### ISSUE THREAD

**Issue by hbrls** [sun-zheng-an/gulp-shell#40]
I'm using shell to run `npm run browserify` where the actual command is `browserify --debug ./src/index.js | exorcist --base ./js ./js/index.js.map > ./js/index.js`.

The error handling of shell is `function (error, stdout, stderr) { if (error) ... }`. When the above command fails, the arguments are like:

    error: null
    stdout: empty string
    stderr: the actual error message

Running only the `browserify` command will throw the error as expected. Piping it to `exorcist` will reproduce what I described above. But the error is from the `browserify` part, not from `exorcist`. So I think it's about piping.

Please checkout my [fork](https://github.com/hbrls/gulp-shell) on branch `browserify`. Run `gulp bug` will reproduce the bug.

**Comment by sun-zheng-an** [comment]
I found `npm run browserify` exited with `0` , so it's a success from the view of `gulp-shell`.
This may be a bug in `npm run`.

**Comment by hbrls** [comment]
@sun-zheng-an Thanks for the hint. The [`pipefail` option](http://stackoverflow.com/a/6872163/707580) should be set to get the expected behavior.

This is not a bug of `gulp-shell`.
