### ISSUE TITLE
`tail -f | grep -v`

### ISSUE THREAD

**Issue by marek-saji** [sun-zheng-an/gulp-shell#44]
I’m trying to add a task that runs `tail -f` on a log file, but exclides some lines (`| grep -v`).

Unfortunatelly this does not work as expected:

```js
gulp.task(
    'log',
    function () {
        return gulp.src('').pipe(shell('tail -n0 -f /var/log/nginx/access.log | grep -Pv "/(img|css|js)/"'));
    }
);
```

However these do:

```js
// no piping
… shell('tail -n0 -f /var/log/nginx/access.log') …
// piping to cat
… shell('tail -n0 -f /var/log/nginx/access.log | cat') …
// no -f attribute to tail
… shell('tail -n0 /var/log/nginx/access.log | grep -Pv "/(img|css|js)/"') …
```

Isn’t this possible with gulp-shell or am I maybe just doing something wrong?

**Comment by sun-zheng-an** [comment]
Could you give me some examples that can reproduce your issue on my own machine?

**Comment by marek-saji** [comment]
I’ve figured it out.

It was actually a problem with `grep` — for some reason, when it's piped it buffers differently (one would think that grep always buffers by line, but no — there’s `--line-buffered` option for that).

In a nutshell this:

```sh
tail -f … | grep … | cat
```

produces output only after `tail -f` gathered more than about 4500 bytes.
On Linux at least.

In case anyone finds this in future — adding `--line-buffered` option to grep solves the problem.


@sun-zheng-an Thank you for being ready to help. {:
