### ISSUE TITLE
Path variable duplication on windows

### ISSUE THREAD

**Issue by malcoriel** [sun-zheng-an/gulp-shell#45]
Example gulpfile, run from windows command promt (Windows 7, node v0.12.2, gulp-shell v0.4.1)

> var gulp = require('gulp');
> var shell = require('gulp-shellexec');
> gulp.task('_testexec', shell.task('cmd /k "set Pa"'));

Shows that there are Path and PATH variables, which causes problems for programs that were run from gulp-shell. For example, .NET Process.Start method will fail with an exception:

> Item has already been added. Key in dictionary: 'Path'  Key being added: 'PATH' --->  > System.ArgumentException: Item has already been added. Key in dictionary: 'Path'  Key being added: > 'PATH'
>   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
>   at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()

It seems that it's caused by line 29 in index.js:

> options.env = _.extend({}, process.env, {PATH: PATH}, options.env)

I use the following replacement:

> var pathKey = _.findKey(process.env, function(val, key){return key.toLowerCase() === 'path'}) || 'PATH';
>  options.env = _.extend({}, process.env, options.env);
> options.env[pathKey] = PATH;

**Comment by luisrudge** [comment]
I'm having this problem too. Any thoughts?

**Comment by luisrudge** [comment]
created a PR with your fix @malcoriel

**Comment by sun-zheng-an** [comment]
Does the `PATH` variable call `Path` by default in Windows?

**Comment by sun-zheng-an** [comment]
@malcoriel @luisrudge I try to fix this issue by a5f68dc3c32e998023612e6aca568150d85403cf .

Could you test it for me?

**Comment by luisrudge** [comment]
@sun-zheng-an Yes! This fixes the problem too

**Comment by luisrudge** [comment]
Let me know when you publish a new version, so I can point my dependency to your package again. thanks!

**Comment by sun-zheng-an** [comment]
@luisrudge `0.4.2` released.

**Comment by luisrudge** [comment]
thanks!
