### ISSUE TITLE
Make it emit('end')

### ISSUE THREAD

**Issue by igorklopov** [sun-zheng-an/gulp-shell#5]
In my case _gulp-shell_ is last in pipeline. _gulp.dest_ is not needed because the utility, that _gulp-shell_ runs, already outputs the final file.

Also, the script should do something with the final file after _gulp-shell_ finishes. So, i use `.once('end', function`. But it seems that `.pipe(shell(...))` does not emit 'end'.

What can i do? May be it is better to make _gulp-shell_ work instead of _gulp.dest_?

**Comment by pixelshaded** [comment]
I am also not getting the end event. There are two ways to create async tasks in gulp. One is to return a stream. The other is to call the callback function. So in your example:

```
gulp.task('shell:staging2', function (callback) {
  var stream = gulp.src('')
    .pipe(shell('your command'));
  stream.on('end', callback);
  stream.resume();
})
```

Resume should consume the data on the readible stream, which should cause the stream from the shell plugin to emit end but I'm not getting it either.

**Comment by jpdevries** [comment]
What if you want a callback for something like this?

```js
gulp.task('shorthand', shell.task([
  'echo hello',
  'echo world'
]))
```

**Comment by dimofte** [comment]
@jpdevries , `shell.task` returns an argument-less function which in turn returns a stream. 
So you can have a gulp task with callback like this:
```
gulp.task('foo', done => {
   shell.task([
      'echo hello',
      'echo world',
   ])().on('finish', done);
});
```

**Comment by tiagoporto** [comment]
@dimofte 
I tried your example, but I receive this error, could you help?

```sh
TypeError: Cannot read property 'on' of undefined
```

```js
import shell from 'gulp-shell'
import eslint from 'gulp-eslint'

gulp.task('scripts:lint', () => {
  return gulp
    .src(path.join(paths.scripts.src, '**/*.{js,jsx}'))
    .pipe(eslint())
    .pipe(eslint.format())
})

gulp.task('scripts', ['scripts:lint'], done => {
  shell.task('npm run scripts')().on('finish', done)
})
```

```
"gulp": "3.9.1",
"gulp-shell": "^0.6.3",
"gulp-eslint": "4.0.0"
```

**Comment by dimofte** [comment]
Apologies for the lateness of the reply, @tiagoporto 
That was an older version of `gulp-shell`. Meanwhile, I can see that `shell.task` has changed to the better and currently (`v0.65`), it's aware of `done`: see [here](https://github.com/sun-zheng-an/gulp-shell/blob/0.6.5/index.js#L97)

So it seems to me that all you need to do in that case is 
```
gulp.task('scripts', ['scripts:lint'], shell.task('npm run scripts'))
```

**Comment by tiagoporto** [comment]
Thanks @dimofte

**Comment by outaTiME** [comment]
@dimofte Im using version v0.7x in the following way:

```js
gulp.task('git:release', async(callback) => {
  const sentry_releases_cmd = `./node_modules/.bin/sentry-cli --auth-token ${sentry_auth_token} releases -o ${sentry_organization} -p ${sentry_project}`;
  await $.shell.task([
    'git add -A',
    `git commit -a -m 'Version ${version} released.'`,
    'git push',
    'git checkout master',
    'git pull',
    'git merge --no-ff develop',
    `git tag ${version}`,
    'git push && git push --tags',
    'git checkout develop',
    // sentry
    `${sentry_releases_cmd} new --finalize ${sentry_version}`,
    `${sentry_releases_cmd} set-commits --auto ${sentry_version}`,
    `${sentry_releases_cmd} files ${sentry_version} upload-sourcemaps --url-prefix '~/build' .tmp/sentry --rewrite`
  ]/*, {quiet: true}*/)();
  callback();
});
```

I hope it helps you
