### ISSUE TITLE
running multiple task not working

### ISSUE THREAD

**Issue by ashish-soni** [sun-zheng-an/gulp-shell#51]
gulp_shell.task([
    'pkill -f proxy-server.js',
    'pkill -f http-server',
    'nohup node proxy-server.js &',
    'nohup http-server -c-1 src -P http://localhost:5050 &'
    ],{
        ignoreErrors: true
    }
)

The command no 4 never executes.

I did walkthrough the library code and found that it invokes child_process.exec  and waits for process finished callback to execute the subsequent command in the list.

In my case 3rd command is long running process which will never exit and so 4th command will never execute.

I think for such long running tasks , one can listen to process started signal and move to next task in the list.

**Comment by jimdoescode** [comment]
I'm having a similar issue. The first few commands run as expected but the following commands don't.
