### ISSUE TITLE
Update deps to latest version - specifically lodash

### ISSUE THREAD

**Issue by mikelax** [sun-zheng-an/gulp-shell#56]
Lodash has been updated to version 3.10.0. There are a few other libs that are out of date, but it would be nice to get lodash updated to current. Would you consider changing support from ~ to ^ for lodash?

**Comment by zacronos** [comment]
+1, I'm having trouble with my app because gulp-shell won't accept lodash 3.10.1, changing from `~3.9.3` to `^3.9.3` is exactly the correct solution, @sun-zheng-an if I submit a PR for this would you accept it?

**Comment by sun-zheng-an** [comment]
Sorry for the delay, I would update it soon.

**Comment by zacronos** [comment]
Ah, great to hear!  In the meantime, I've made a PR for this: https://github.com/sun-zheng-an/gulp-shell/pull/58

**Comment by ar7casper** [comment]
Hi, 

It's been a while since Aug 29, 2015, any chance that you will update lodash to 4.0.0?

BR,
