### ISSUE TITLE
Task does not exit when running under a docker container without allocating a pseudo-tty

### ISSUE THREAD

**Issue by demetriusnunes** [sun-zheng-an/gulp-shell#57]
I am running serveral gulp tasks, under docker containers, inside Jenkins jobs.

If I disable pseudo-tty allocation (required for jenkins for capturing the output of jobs), running a gulp shell task does not exit when using the shorthand notation.

Here are the commands I am running:

```
# -T option disables pseudo-tty allocation
docker-compose run -T api sh -c 'gulp migration'

gulp.task('migration', shell.task('mongo db:27017/ctrldb ./migrations/channels.js'));
```

**Comment by alexandercastillo** [comment]
+1

**Comment by sun-zheng-an** [comment]
@demetriusnunes 
Sorry for my long delay.
Could you update your `gulp-shell` to version `0.5.0` to see whether it fix this issue?
