### ISSUE TITLE
Issue with gulp-shell with kss-node

### ISSUE THREAD

**Issue by joaogarin** [sun-zheng-an/gulp-shell#60]
Hello,

I am having an issue with gulp-shell. I have the following task : 

gulp.task('styleguide-kss',['compile-styleguide'], shell.task([
    'kss-node <%= source %> <%= destination %> --template <%= template %> --css <%= cssfile %>'
  ], {
    templateData: {
      source:       paths.styleguide.source,
      destination:  'styleguide/docs',
      template:     paths.styleguide.template,
      cssfile:     'css/styles.css'
    }
  }
));

It fails with the message that command failed with code 1. If I run the command manually via kss-node (the same command in the output messsage exactly) it works fine.

Any idea what the problem might be?

Best regards

**Comment by JohnAlbin** [comment]
Something must be wrong with your paths. But you haven't posted that info here.

Double check that paths.styleguide.source and  paths.styleguide.template are strings and not arrays of strings.

**Comment by joaogarin** [comment]
Yeah sorry It totally works! sorry to keep it open for so long..Closing it!
