### ISSUE TITLE
standard in not working for me in 0.4.3

### ISSUE THREAD

**Issue by chrisfelix82** [sun-zheng-an/gulp-shell#61]
I used this version the other day and it was accepting stdin and now appears to be hanging.  Any thoughts?

**Comment by sun-zheng-an** [comment]
I found it works at least for this simple case.

    gulp.task('default', shell.task('read foo && echo $foo'))

**Comment by chrisfelix82** [comment]
It appears to be intermittent. I am trying with Ionic. I run gulp.task("ionic-run",plugins.shell.task(['cd ionicapp && ionic run ---livereload -c']);  when I get prompted to select a livereload server hostname it sometimes does not work.
