### ISSUE TITLE
Tasks using gulp-shell hang when run from Bamboo CI

### ISSUE THREAD

**Issue by ndonald2** [sun-zheng-an/gulp-shell#63]
I'm using `gulp-shell` for a number of tasks that are run in a Bamboo CI plan. However, these tasks always seem to hang my Bamboo agents, forcing me to manually abort the builds.

The gulp task prints that it is finished, but it apparently never returns control to the build agent. The only way I've been able to get this to work is by adding `process.exit(0);` in a stream end event handler for the offending gulp tasks. This does not happen with any gulp tasks that do not use `gulp-shell`.

Any thoughts? Here's an example:

```javascript
gulp.task('lint', function() {
  return gulp.src([
      '**/*.py',
      '!node_modules/**/*.py',
    ], {
      read: false
    })
    .pipe(shell([
      'echo \"Linting <%= file.path %>...\"',
      'pylint <%= file.path %> -E'
    ]))
    .on('error', function() {
      gutil.log(gutil.colors.red('LINTING FAILED'));
      process.exit(1);
    })
    .on('end', function() {
      process.exit(0); // Force bamboo task to end
    });
});
```

**Comment by agentschmitt** [comment]
i think it could be same problem as https://github.com/sun-zheng-an/gulp-shell/issues/59
try version 0.4.0 this could solve your problem

**Comment by sun-zheng-an** [comment]
I just released `0.5.0`, it should fix all the issues like this one (running non-interactive commands and doesn't end properly at the end).

Please check it out.

**Comment by ndonald2** [comment]
Seems to work now! Thanks!

**Comment by mmilczewski** [comment]
In version `0.5.1` this problem returned.
In `0.5.0` everything works.

**Comment by sun-zheng-an** [comment]
@mmilczewski Could you give me some code to reproduce it?
