### ISSUE TITLE
interactive task does not finish the task

### ISSUE THREAD

**Issue by marcingasior** [sun-zheng-an/gulp-shell#66]
Hello,

I have to run a deployment shell script, which at one point prompt for y/n question, the shell task continues as expected, till script prints done message, than it fails to emit stop.

**Comment by simevidas** [comment]
I have a similar problem:

    gulp.task('deploy', ['build-css', 'build-js'], shell.task('modulus deploy'));
    
![test](https://cloud.githubusercontent.com/assets/716405/10562560/bc4ba81e-7561-11e5-940f-72380e1ab400.png)

**Comment by sun-zheng-an** [comment]
@simevidas Did you turn on the [`interactive`](https://github.com/sun-zheng-an/gulp-shell#optionsinteractive) option?

**Comment by simevidas** [comment]
@sun-zheng-an Thanks :) I'll keep this in mind.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
+1
I have a similar problem where my script asks multiple questions and fails to exit after the last one is entered.  The "Enter" key simply acts as a newline. This can be replicated by doing the following:
```
Gulp.task( 'setup-commands', Shell.task(
    [
        'npm init'
    ], {
        interactive: true
    })
);
```

**Comment by creat-or** [comment]
same thing, doesn't exit with interactive=true, but only if user had to interact.
