### ISSUE TITLE
Gulp 4 and "Did you forget to signal async completion?"

### ISSUE THREAD

**Issue by ksnyde** [sun-zheng-an/gulp-shell#70]
When I use gulp.shell with Gulp 4, what is the correct syntax? All attempts I've made using Gulp 4 seem to fail with the following gulp error:

> Did you forget to signal async completion?

Here's a simple example of Gulp 3 task which worked:

    gulp.task('npmInstall', shell.task[
      'echo Installing dependencies',
      'npm install my-package'
    ]);

I had hoped to just do something like:

    gulp.task('npmInstall', gulp.series(()=> {
      shell.task[
        'echo Installing dependencies',
        'npm install my-package'
      ];
    }));

but this is an example of where I get this error. I've tried a few other approaches but nothing seems to work. :(

**Comment by sun-zheng-an** [comment]
Please try:

```
gulp.task('npmInstall', gulp.series(shell.task([...])))
```

**Comment by ksnyde** [comment]
thanks. works.
