### ISSUE TITLE
shell tasks are all run independently from the same root without continuity

### ISSUE THREAD

**Issue by mix3d** [sun-zheng-an/gulp-shell#71]
I want to be able to do something like 
`gulp.task('taskname',shell.task(['cd dir','git checkout master','git pull', 'cd ..', ... etc]));`
However, each task ends and a new one starts from the same base folder; there is no continuation of the flow of tasks.

I managed to make it work by concatenating them with semicolons, but it feels wrong.

**Comment by sun-zheng-an** [comment]
Just [join](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) the array by `;` or `&&`.

**Comment by mix3d** [comment]
Like I said, `;` works, but doing them in an array is visually more appealing to the code.
