### ISSUE TITLE
gulp-shel not working on windows 7

### ISSUE THREAD

**Issue by harilalinapp** [sun-zheng-an/gulp-shell#72]
I have been developing application using requirejs. When i tried to run the r.js command through gulp shel it just simply open a r.js file. but the command works in cmd . 
gulp.task('optimize', shell.task([
    // This is the command
    'r.js -o full-build.js'
]))

**Comment by virgil9306** [comment]
Does anyone know if this plugin only supports Linux-based systems? I would think so... I haven't used it on a Windows machine.
