### ISSUE TITLE
Run gulp-shell with npm init

### ISSUE THREAD

**Issue by pensierinmusica** [sun-zheng-an/gulp-shell#74]
Hi,

I'm trying to run `gulp-shell` with `npm-init`.

This is what my current code looks like:

``` js
gulp.task('init', shell.task('npm init', {interactive: true}));
```

It all works fine, and `package.json` gets created. The only problem I have is that the process never exits, and the `init` gulp task never finishes.

Could you help me figure out what I'm doing wrong?

Thanks!

**Comment by pensierinmusica** [comment]
@sun-zheng-an any update?

**Comment by sun-zheng-an** [comment]
Try `0.6.x`, it should fix issues like this one.

**Comment by pensierinmusica** [comment]
Thanks!
