### ISSUE TITLE
Allow arguments to be passed out-of-band from script text

### ISSUE THREAD

**Issue by charles-dyfis-net** [sun-zheng-an/gulp-shell#83]
Templating filenames as strings into a shell script -- as `gulp-shell` recommends -- is extremely dangerous practice from a security perspective. The best-practice approach is for script text to be hardcoded, and for parameters to be passed out-of-band, as arguments or in the environment. Demonstrating two possible argument vectors with the same literal argument:

    dangerString="/tmp/evil/$(rm -rf $HOME)'$(rm -rf $HOME)'"

    # this argument vector is harmless, and will correctly make a directory with the given name
    ['sh', '-c', 'directory=$1; mkdir -p "$directory", _, dangerString]

    # this argument vector is dangerous, and will destroy the user's home directory
    ['sh', '-c', "mkdir -p <%= dangerString %>"]

Note the literal single quotes in dangerString, such that even putting single quotes around the expansion cannot prevent one or the other of the command substitutions contained within from being expanded.

Not only should a tool that's advertised as a way to call a shell from JavaScript *implement* a safe way to do so, but it should *document and advertise* safe practices as the preferred way to use it.

**Comment by charles-dyfis-net** [comment]
To be clear, by the way, the given `dangerString` value here is a completely legitimate UNIX path, *including* the `$`, and single-quotes. You could thus genuinely receive this as a value from a directory listing or traversal operation.

**Comment by sun-zheng-an** [comment]
> Templating filenames as strings into a shell script -- as gulp-shell recommends -- is extremely dangerous practice from a security perspective.

Yes, I agree with you. It's dangerous.

But considering most (if not all) of the users of `gulp-shell` use it for their own projects, it's very unlikely that we have files named like `$(rm -rf $HOME)` and inject it as an argument to shoot ourself in the foot.

IMHO, injections like `'<%= f(x) %>'` can provide more flexibility than `'directory=$1; mkdir -p "$directory"'` and looks simpler.

Thanks for your advice anyway.

**Comment by pvgoran** [comment]
It's not just dangerous, it can stop things from working if, say, the filename contains a space. (And I suspect this can happen very easily under Windows!)

So, ideally the interpolation operation (`<%= %>` or whatever) needs to shell-escape the value to ensure that the shell will treat it like a single word. This way, it will be at the same time convenient, reliable and safe.

**Comment by charles-dyfis-net** [comment]
Escaping at interpolation time is only safe if you know the escaping context into which those results are going to be used. The escaping that's appropriate for `mycommand 'foo-<% ... %>'` is different from the escaping for `mycommand <% ... %>`, which is again different from that for `mycommand "foo-<% ... %>"`, and since the differences only come up with odd corner cases, it's easy for someone using the tools in an unsafe way to fail to notice until they're hit with unexpected content in production.

Passing data out-of-band from code, by contrast, there is no such thing as an escaping context -- the entire range of issues is moot.

And if gulp-shell is only built to be fit-to-purpose for personal/hobby projects and not security-sensitive use cases, *it should explicitly advertise itself with that limitation*.

**Comment by pvgoran** [comment]
> Escaping at interpolation time is only safe if you know the quoting context into which those results are going to be used.

Yes, that's how any escaping works. :) However, this could at least produce **one** correct way of embedding dynamic data into the shell invocation, without changing the overall usage pattern. And this one correct way can then be explicitly documented. Definitely an improvement over the current situation, when there is no reliable/safe way to embed the data **at all**.

> Passing data out-of-band from code, by contrast, there is no such thing as a quoting context -- the entire range of issues is moot.

To be honest, one can screw the shell command even in such circumstances. For example, if the file name is passed as an environment variable, you can forget to quote it (for example, in `[ $foo = "bar" ]`) and get a problem.

**Comment by charles-dyfis-net** [comment]
"A problem", certainly. Arbitrary code execution, more rarely -- the example given runs an arbitrary `test` command (and certainly, this means someone could pass something like `evil -o bar` instead of `bar` and still have the test for equality with `bar` pass despite those strings not in fact being equal), but "an arbitrary test" is significant, and useful, distance from "an arbitrary command".

---

A solution that split the difference -- offering *both* quoted expansion into a string parsed as code and out-of-band argument-passing, with choice at the user's discretion -- would be well in line with practices in other parts of the world (ie. the Python standard library providing both a `quote()` function *and* the ability to pass an arbitrary argument vector of literal strings even with `shell=True` set in the `subprocess.Popen` family of functions).
