### ISSUE TITLE
Error with gcloud commands: [Errno 35] Resource temporarily unavailable

### ISSUE THREAD

**Issue by mikelambert** [sun-zheng-an/gulp-shell#84]
I am using `gulp-shell` to run `gcloud app deploy`, which then dies with `[Errno 35] Resource temporarily unavailable`. This does not happen when I run the command directly.

I've found [this issue](https://code.google.com/p/google-cloud-sdk/issues/detail?id=850) describing the problems with `gcloud` and `node` that trigger the errors, and I suspect the answer there might also apply here in some fashion. But it looks like `gulp-shell` uses `exec`, not `spawn`, meaning I'm not sure how to apply this sort of fix.

If this is "not a `gulp-shell` bug", then I suppose I can [use one of these workarounds](http://stackoverflow.com/questions/32623815/simple-gulp-task-to-deploy-to-google-app-engine-and-stream-output-to-console).

**Comment by sun-zheng-an** [comment]
Thanks for the feedback.

`0.6.0` is just released, it may fix this problem.

**Comment by sun-zheng-an** [comment]
Please reopen this issue if `0.6.x` hasn't fixed it.
