### ISSUE TITLE
Unhandled error event on gull-shell ≥ 0.6.0

### ISSUE THREAD

**Issue by wjdp** [sun-zheng-an/gulp-shell#86]
Doing a package upgrade on a project I maintain. Seeing the following with ≥ 0.6.0:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn echo Hello World ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```

Gulpfile to reproduce:

```js
'use strict';

var gulp = require('gulp');
var shell = require('gulp-shell');

var SHELL_OPTS = { verbose: true };

gulp.task('hello', shell.task(['echo Hello World'], SHELL_OPTS))
```

Environment, package versions here: https://github.com/newtheatre/history-project/blob/91ccd325b98066e94c28f65b6cb56ea517a0e3f5/package.json

Same Gulpfile works under 0.5.2:

```
[19:23:16] Using gulpfile ~/local/history-project/gulpfile.js
[19:23:16] Starting 'hello'...
[19:23:16] echo Hello World
Hello World
[19:23:16] Finished 'hello' after 22 ms
```

**Comment by sun-zheng-an** [comment]
Which Node.js version do you use?

**Comment by wjdp** [comment]
Node is v4.2.6

**Comment by wjdp** [comment]
Tried on v6.10.0, works

**Comment by sun-zheng-an** [comment]
Oh, I found that I had used a feature added in `Node 6.0` https://github.com/nodejs/node/commit/c3bb4b1aa5e907d489619fb43d233c3336bfc03d , which it's the key change of `gulp 0.6.0`.

Thanks for the feedback. I will update the README for this.

**Comment by wjdp** [comment]
Fab, thanks for the quick responses!

**Comment by expobrain** [comment]
Actually is failing on Node 5.4.1 as well

**Comment by sun-zheng-an** [comment]
@expobrain 

Thanks for your feedback!

I have forgotten to require Node `> 5.7.0` for `5.x`.

You need to upgrade your Node to fix this, sorry for the inconvenience.

**Comment by expobrain** [comment]
Yep, 5.7.0 is the minimum supported version for `gulp-shell` >= 0.6

**Comment by grofit** [comment]
I just ran into this issue on our CI server as it was baffling why it worked locally, is there any way to check the node version and just throw an error saying the node version is too old or something?

**Comment by expobrain** [comment]
Just made a PR to stop the installation of this package if the node's version doesn't match
