### ISSUE TITLE
Running gulp-shell in win32 environment causes duplicate environment keys

### ISSUE THREAD

**Issue by ti24horas** [sun-zheng-an/gulp-shell#88]
I tried the following test:
``` javascript
gulp.task('print_vars', ()=>gulp.src('src').pipe(shell('env')));

 ```

It returns two times the PATH variable.

This cause issues when running dotnet commands.

May I send you a PR to solve that?

**Comment by sun-zheng-an** [comment]
PRs are always welcome.
