### ISSUE TITLE
Not changing directory in shell task

### ISSUE THREAD

**Issue by powdevel** [sun-zheng-an/gulp-shell#92]
Hi! I was trying a very simple script but the directory is not changing. The result of ls is the same contents of the directory where the script was executed. 
```
gulp.task('shorthand', shell.task([
  'cd web',
  'ls',
]))

```

**Comment by sun-zheng-an** [comment]
Because each command in the array is executed in its own context, you can fix it by joining them with `&&` like:

```js
[
  'cd web',
  'ls'
].join(' && ')
```
