### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by chrisfinazzo** [sun-zheng-an/gulp-shell#97]
I get this error when trying to run one of the tasks in my Gulpfile. Is there a specific way to pass a filename inside `shell.task`? Failing that, I suspect the `=` may be at fault. Usually I just run this as a one liner, and Bash does its thing without complaining.

    gulp.task('deploy', shell.task('rsync -crz --exclude-from='rsync-exclude.txt' --delete _site/ cfinazzo1@micro.chrisfinazzo.com:/home/cfinazzo1/micro.chrisfinazzo.com'));

**Comment by sun-zheng-an** [comment]
Try to change the outmost `'` into `"`.

**Comment by chrisfinazzo** [comment]
Yes, that does it. Thanks.
