### ISSUE TITLE
Exit code 1 doesn't stop execution

### ISSUE THREAD

**Issue by reintroducing** [sun-zheng-an/gulp-shell#98]
I've got a script that looks like this in my package.json file:
`"build": "rm -rf lib || true && mkdir lib && cypress run && babel src -d lib --ignore *.spec.js"`

Specifically, that `cypress run` task is a test runner that has a failing test. This fails the whole script and the subsequent `babel` portion does not execute. Great.

The problem is that my actual, unedited script, looks like this:
`"build": "rm -rf lib || true && mkdir lib && ace -- cypressRun && babel src -d lib --ignore *.spec.js"`

Here you can see that `cypress run` has been replaced with `ace -- cypressRun` which is a CLI that essentially extracts out gulp/webpack/etc from a project. The particular `cypressRun` task is this, under the hood:
```
const cypressRunTask = () => {
    return shell.task([
        'cypress run'
    ], {
        cwd: process.env.INIT_CWD
    });
};
```

When the `build` script is run in this manner, I see the error message but the subsequent `babel` script is still being executed.
```
[10:58:42] 'cypressRun' errored after 17 s
[10:58:42] Error in plugin "gulp-shell"
Message:
    Command `cypress run` failed with exit code 1
// and then the rest of the output from the build script
src/animation/animation.js -> lib/animation/animation.js
src/api/api.js -> lib/api/api.js
// ...etc
```

Is there any way to make `gulp-shell` stop the rest of the script's commands if the exit code it reports is 1?

**Comment by sun-zheng-an** [comment]
> Is there any way to make gulp-shell stop the rest of the script's commands if the exit code it reports is 1?

This is exactly how `gulp-shell` handle failed commands.

> Here you can see that `cypress run` has been replaced with `ace -- cypressRun` which is a CLI that essentially extracts out gulp/webpack/etc from a project.

I suspect that `ace -- cypressRun` always exits with 0 even when `cypress run` failed.
